import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CarmelitasRecipesService {
  recetas: any=[
    {
      img: '../../../assets/images/carmelitas-recipes/rompopes-milkshake/malteada-rompope.png',
      nombre:"Rompope's Milkshake",
      descripcion:"Delicious vanilla milkshake with Carmelita’s Rompope (Mexican's Eggnog)",
      alt:"Image of vanilla shake with Carmelita's Rompope",
      linkVideo: 'https://www.youtube.com/watch?v=BtXwWCpRz3I',
      ingrediente1: "1.- 1⁄2 cup of Carmelita’s rompope",
      ingrediente2: ' 2.- 2 small balls of vanilla ice cream',
      ingrediente3: ' 3.- 1 cup of almond milk',
      pr1: '1.- Empty the 1⁄2 cup of rompope to the blender.',
      pr2: '2.- Add the vanilla ice cream small balls.',
      pr3: '3.- We blend for 30sec.',
      pr4: '4.- We serve and enjoy.',
      galeria1: '.../../../assets/images/carmelitas-recipes/rompopes-milkshake/gallery/1.png',
      galeriaalt1: "Image of the preparation of the Rompope's milkshake 1",
      galeria2: '.../../../assets/images/carmelitas-recipes/rompopes-milkshake/gallery/2.png',
      galeriaalt2: "Image of the preparation of the Rompope's milkshake 2",
      galeria3: '.../../../assets/images/carmelitas-recipes/rompopes-milkshake/gallery/3.png',
      galeriaalt3: "Image of the preparation of the Rompope's milkshake 3",
      galeria4: '.../../../assets/images/carmelitas-recipes/rompopes-milkshake/gallery/4.png',
      galeriaalt4: "Image of the preparation of the Rompope's milkshake 4",
      galeria5: '.../../../assets/images/carmelitas-recipes/rompopes-milkshake/gallery/5.png',
      galeriaalt5: "Image of the preparation of the Rompope's milkshake 5",
      galeria6: '.../../../assets/images/carmelitas-recipes/rompopes-milkshake/gallery/6.png',
      galeriaalt6: "Image of the preparation of the Rompope's milkshake 6",
      galeria7: '.../../../assets/images/carmelitas-recipes/rompopes-milkshake/gallery/7.png',
      galeriaalt7: "Image of the preparation of the Rompope's milkshake 7",
      galeria8: '.../../../assets/images/carmelitas-recipes/rompopes-milkshake/gallery/8.png',
      galeriaalt8: "Image of the preparation of the Rompope's milkshake 8",

    },
    {
      img: '../../../assets/images/carmelitas-recipes/carmelitas-jelly/gelatina-rompope.png',
      nombre:"Carmelita's Jelly",
      descripcion:"Delicious jelly with Carmelita’s Rompope",
      alt:"Image of Carmelita's jelly",
      linkVideo: 'https://www.youtube.com/watch?v=4W-IcN4urkk',
      ingrediente1: "1.- 1 1⁄2 cup of Carmelita's Rompope",
      ingrediente2: '2.- 2 tablespoons of gelatin',
      ingrediente3: '3.- 1 cup of cold water',
      ingrediente4: '4.- Butter',
      ingrediente5: '5.- 1⁄2 cup of cold water',
      ingrediente6: ' 6.- 1 cup of sugar',
      pr1: '1.- Place the cup of water in a container',
      pr2: '2.- Later we put the gelatin in the container of water and we move well.',
      pr3: '3.- We place 2 cups of water in another container and add the cup of sugar, put on the fire until it boils.',
      pr4: '4.- Once it boils, add the gelatin and stir so that it dissolves well.',
      pr5: '5.- We are preparing the mold where we will put the mixture of water, gelatin and sugar. Where we will spread a little butter before placing (this so that it does not stick)',
      pr6: '6.- Once the mixture is cold, we place the eggnog and mix.',
      pr7: '7.- We put everything in the mold, once everything is mixed and put in the refrigerator.',
      pr8: '8.- We leave in the refrigerator for a few hours.',
      pr9: '9.- Take out of the mold and enjoy.',
      galeria1: '.../../../assets/images/carmelitas-recipes/carmelitas-jelly/gallery/1.png',
      galeriaalt1: "Image of the preparation of Carmelita's jelly 1",
      galeria2: '.../../../assets/images/carmelitas-recipes/carmelitas-jelly/gallery/2.png',
      galeriaalt2: "Image of the preparation of Carmelita's jelly 2",
      galeria3: '.../../../assets/images/carmelitas-recipes/carmelitas-jelly/gallery/3.png',
      galeriaalt3: "Image of the preparation of Carmelita's jelly 3",
      galeria4: '.../../../assets/images/carmelitas-recipes/carmelitas-jelly/gallery/4.png',
      galeriaalt4: "Imagen de la preparación de la gelatina Carmelita 4",
      galeria5: '.../../../assets/images/carmelitas-recipes/carmelitas-jelly/gallery/5.png',
      galeriaalt5: "Image of the preparation of Carmelita's jelly 5",
      galeria6: '.../../../assets/images/carmelitas-recipes/carmelitas-jelly/gallery/6.png',
      galeriaalt6: "Image of the preparation of Carmelita's jelly 6",
      galeria7: '.../../../assets/images/carmelitas-recipes/carmelitas-jelly/gallery/7.png',
      galeriaalt7: "Image of the preparation of Carmelita's jelly 7",
      galeria8: '.../../../assets/images/carmelitas-recipes/carmelitas-jelly/gallery/8.png',
      galeriaalt8: "Image of the preparation of Carmelita's jelly 8",
    },
    {
      img: '../../../assets/images/carmelitas-recipes/rompopes-cake/pastel3leches-rompope.png',
      nombre:"Rompope's Cake",
      descripcion:"Delicious Rompope's Cake",
      alt:"Image of delicious Rompope's Cake",
      linkVideo: 'https://www.facebook.com/RompopeCarmelita/posts/2145649825579479',
      ingrediente1: '1.- 5 egg whites',
      ingrediente2: '2.- 3⁄4 cups of sugar, for the whites',
      ingrediente3: '3.- 5 egg yolks',
      ingrediente4: '4.- 3⁄4 cups of sugar, for the yolks',
      ingrediente5: "5.- 1⁄2 cups of cow's milk",
      ingrediente6: '6.- 1 teaspoon of liquid vanilla',
      ingrediente7: '7.- 1 teaspoon of lemon zest',
      ingrediente8: '8.- 1 1⁄2 cups of flour',
      ingrediente9: '9.- 1 teaspoon of baking powder',
      ingrediente10: '10.- 1 cup of condensed milk, for the three milks',
      ingrediente11: '11.- 1 cup of evaporated milk, for the three milks',
      ingrediente12: '12.- 1 cup of whole milk, for the three milks',
      ingrediente13: "13.- 1⁄4 cups of Carmelita's Rompope, for the three milks",
      ingrediente14: '14.- 2 cups of whipped cream',
      ingrediente15: '15.- to taste of strawberry, to decorate',
      ingrediente16: '16.- to taste of mint, to decorate',
      pr1: '1.- Preheat the oven to 180 ° C.',
      pr2: '2.- For the cake, beat the whites with the sugar to the point of nougat.',
      pr3: '3.- Beat the egg yolks with the sugar until they change color, add the milk, vanilla and dry ingredients little by little, using a strainer.',
      pr4: '4.- Add the whites in an enveloping way to the previous mixture.',
      pr5: '5.- Pour the preparation into two cake molds, previously greased and floured, bake for 25 minutes. Let cool and reserve.',
      pr6: '6.- For the three milks, mix the condensed milk, the evaporated milk, the whole milk and the eggnog.',
      pr7: '7.- With the help of a fork, chop a cake and pour the three milks, refrigerate for 1 hour, place whipped cream on the cake, place the other cake on top, chop with a fork and with the help of a brush, dip three milks.',
      pr8: '8.- With the help of a spatula, cover the cake with the remaining whipped cream, decorate with strawberries and mint.',
      galeria1: '.../../../assets/images/carmelitas-recipes/rompopes-cake/gallery/1.png',
      galeriaalt1: "Image of the Melón y Sandía's girls cooking the Rompope's Cake 1",
      galeria2: '.../../../assets/images/carmelitas-recipes/rompopes-cake/gallery/2.png',
      galeriaalt2: "Image of the Melón y Sandía's girls cooking the Rompope's Cake 2",
      galeria3: '.../../../assets/images/carmelitas-recipes/rompopes-cake/gallery/3.png',
      galeriaalt3: "Image of the Melón y Sandía's girls cooking the Rompope's Cake 3",
      galeria4: '.../../../assets/images/carmelitas-recipes/rompopes-cake/gallery/4.png',
      galeriaalt4: "Image of the Melón y Sandía's girls cooking the Rompope's Cake 4",
      galeria5: '.../../../assets/images/carmelitas-recipes/rompopes-cake/gallery/5.png',
      galeriaalt5: "Image of the Melón y Sandía's girls cooking the Rompope's Cake 5",
      galeria6: '.../../../assets/images/carmelitas-recipes/rompopes-cake/gallery/6.png',
      galeriaalt6: "Image of the Melón y Sandía's girls cooking the Rompope's Cake 6",
      galeria7: '.../../../assets/images/carmelitas-recipes/rompopes-cake/gallery/7.png',
      galeriaalt7: "Image of the Melón y Sandía's girls cooking the Rompope's Cake 7",
      galeria8: '.../../../assets/images/carmelitas-recipes/rompopes-cake/gallery/8.png',
      galeriaalt8: "Image of the Melón y Sandía's girls cooking the Rompope's Cake 8",
    },
    {
      img: '../../../assets/images/carmelitas-recipes/carmelitas-crepe-cake/pastelcrepas-rompope.png',
      nombre:"Carmelita's Crepe Cake",
      descripcion:"Delicious Carmelita's Crepe Cake",
      alt:"Image of delicious Carmelita's Crepe Cake",
      linkVideo: 'https://www.youtube.com/watch?v=SsiUKH7MH08',
      ingrediente1: '2 tazas de leche de vaca',
      ingrediente2: '1 taza de harina',
      ingrediente3: '1/4 de taza de mantequilla fundida',
      ingrediente4: '2 huevos',
      ingrediente5: '1/8 de taza de azúcar',
      ingrediente6: '1 cucharadita de vainilla líquida',
      ingrediente7: '1 cucharadita de canela en polvo',
      ingrediente8: '3 tazas de crema para batir',
      ingrediente9: '3 cucharadas de ralladura de limón amarillo',
      ingrediente10: '3 tazas de fresa, cortadas en láminas',
      pr1: '1.- En un bowl mezcla todos los ingredientes de las crepas hasta formar un mezcla homogénea.',
      pr2: '2.- Calienta una sartén a fuego medio y forma crepas hasta conseguir el número de crepas deseadas para las capas del pastel.',
      pr3: '3.- En un bowl bate la crema para batir hasta que doble su volumen, agrega la ralladura de limón, el jugo de limón y el azúcar glass.',
      pr4: '4.- En un plato coloca una crepa de base, unta una capa de crema batida y agrega fresas. Repite hasta formar varias capas.',
      pr5: '5.- Cubre todo el pastel con crema batida, decora la parte de arriba con abundantes fresas. Refrigera 1 hora, sirve y disfruta.',
      galeria1: '.../../../assets/img/galeria-recetas/chef-oliver/1.png',
      galeriaralt1: "Imágenes del chef Oliver y Pastel de Crepas 1",
      galeria2: '.../../../assets/img/galeria-recetas/chef-oliver/2.png',
      galeriaalt2: "Imágenes del chef Oliver y Pastel de Crepas 2",
      galeria3: '.../../../assets/img/galeria-recetas/chef-oliver/3.png',
      galeriaalt3: "Imágenes del chef Oliver y Pastel de Crepas 3",
      galeria4: '.../../../assets/img/galeria-recetas/chef-oliver/4.png',
      galeriaalt4: "Imágenes del chef Oliver y Pastel de Crepas 4",
      galeria5: '.../../../assets/img/galeria-recetas/chef-oliver/5.png',
      galeriaalt5: "Imágenes del chef Oliver y Pastel de Crepas 5",
      galeria6: '.../../../assets/img/galeria-recetas/chef-oliver/6.png',
      galeriaalt6: "Imágenes del chef Oliver y Pastel de Crepas 6",
      galeria7: '.../../../assets/img/galeria-recetas/chef-oliver/7.png',
      galeriaalt7: "Imágenes del chef Oliver y Pastel de Crepas 7",
      galeria8: '.../../../assets/img/galeria-recetas/chef-oliver/8.png',
      galeriaalt8: "Imágenes del chef Oliver y Pastel de Crepas 8",
      
    } 
      
  ]
  constructor() { }
  obtenerReceta(){
    return this.recetas;
  }
  obtenerUno(i){
    return this.recetas[i];
  }
}
