import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CarmelitasMomentsService {
  momentosc: any = [
    {
      album: 'Capula',
      portada: '../../../assets/images/carmelitas-moments/capula/13.png',
      descportada: 'Cover image of trip to Capula',
      img1: '../../../assets/images/carmelitas-moments/capula/1.png',
      alt1:'Image of trip to Capula 1',
      img2: '../../../assets/images/carmelitas-moments/capula/2.png',
      alt2:'Image of trip to Capula 2',
      img3:'../../../assets/images/carmelitas-moments/capula/3.png',
      alt3:'Image of trip to Capula 3',
      img4: '../../../assets/images/carmelitas-moments/capula/4.png',
      alt4:'Image of trip to Capula 4',
      img5:'../../../assets/images/carmelitas-moments/capula/5.png',
      alt5:'Image of trip to Capula 5',
      img6: '../../../assets/images/carmelitas-moments/capula/6.png',
      alt6:'Image of trip to Capula 6',
      img7:'../../../assets/images/carmelitas-moments/capula/7.png',
      alt7:'Image of trip to Capula 7',
      img8:'../../../assets/images/carmelitas-moments/capula/8.png',
      alt8:'Image of trip to Capula 8',
      img9:'../../../assets/images/carmelitas-moments/capula/9.png',
      alt9:'Image of trip to Capula 9',
      img10:'../../../assets/images/carmelitas-moments/capula/10.png',
      alt10:'Image of trip to Capula 10',
      img11:'../../../assets/images/carmelitas-moments/capula/11.png',
      alt11:'Image of trip to Capula 11',
      img12:'../../../assets/images/carmelitas-moments/capula/12.png',
      alt12:'Image of trip to Capula 12',
      img13:'../../../assets/images/carmelitas-moments/capula/13.png',
      alt13:'Image of trip to Capula 13',
      img14:'../../../assets/images/carmelitas-moments/capula/14.png',
      alt14:'Image of trip to Capula 14',
      img15:'../../../assets/images/carmelitas-moments/capula/15.png',
      alt15:'Image of trip to Capula 15',
      img16:'../../../assets/images/carmelitas-moments/capula/16.png',
      alt16:'Image of trip to Capula 16',
      img17:'../../../assets/images/carmelitas-moments/capula/17.png',
      alt17:'Image of trip to Capula 17',
    },
    {
      album: 'Death Day',
      portada: '../../../assets/images/carmelitas-moments/death-day/12.png',
      descportada: "Cover image of Carmelita's Death Day",
      img1: '../../../assets/images/carmelitas-moments/death-day/1.png',
      alt1:"Image of Carmelita's Death Day 1",
      img2: '../../../assets/images/carmelitas-moments/death-day/2.png',
      alt2:"Image of Carmelita's Death Day 2",
      img3:'../../../assets/images/carmelitas-moments/death-day/3.png',
      alt3:"Image of Carmelita's Death Day 3",
      img4: '../../../assets/images/carmelitas-moments/death-day/4.png',
      alt4:"Image of Carmelita's Death Day 4",
      img5:'../../../assets/images/carmelitas-moments/death-day/5.png',
      alt5:"Image of Carmelita's Death Day 5",
      img6: '../../../assets/images/carmelitas-moments/death-day/6.png',
      alt6:"Image of Carmelita's Death Day 6",
      img7:'../../../assets/images/carmelitas-moments/death-day/7.png',
      alt7:"Image of Carmelita's Death Day 7",
      img8:'../../../assets/images/carmelitas-moments/death-day/8.png',
      alt8:"Image of Carmelita's Death Day 8",
      img9:'../../../assets/images/carmelitas-moments/death-day/9.png',
      alt9:"Image of Carmelita's Death Day 9",
      img10:'../../../assets/images/carmelitas-moments/death-day/10.png',
      alt10:"Image of Carmelita's Death Day 10",
      img11:'../../../assets/images/carmelitas-moments/death-day/11.png',
      alt11:"Image of Carmelita's Death Day 11",
      img12:'../../../assets/images/carmelitas-moments/death-day/12.png',
      alt12:"Image of Carmelita's Death Day 12",
      img13:'../../../assets/images/carmelitas-moments/death-day/13.png',
      alt13:"Image of Carmelita's Death Day 13",
      img14:'../../../assets/images/carmelitas-moments/death-day/14.png',
      alt14:"Image of Carmelita's Death Day 14",
      img15:'../../../assets/images/carmelitas-moments/death-day/15.png',
      alt15:"Image of Carmelita's Death Day 15",
      img16:'../../../assets/images/carmelitas-moments/death-day/16.png',
      alt16:"Image of Carmelita's Death Day 16",
      img17:'../../../assets/images/carmelitas-moments/death-day/17.png',
      alt17:"Image of Carmelita's Death Day 17",
    },
    {
      album: "Carmelita's Factory",
      portada: '../../../assets/images/carmelitas-moments/carmelitas-factory/13.png',
      descportada: "Cover image at Carmelita's Factory",
      img1: '../../../assets/images/carmelitas-moments/carmelitas-factory/1.png',
      alt1:"Image at Carmelita's Factory 1",
      img2: '../../../assets/images/carmelitas-moments/carmelitas-factory/2.png',
      alt2:"Image at Carmelita's Factory 2",
      img3:'../../../assets/images/carmelitas-moments/carmelitas-factory/3.png',
      alt3:"Image at Carmelita's Factory 3",
      img4: '../../../assets/images/carmelitas-moments/carmelitas-factory/4.png',
      alt4:"Image at Carmelita's Factory 4",
      img5:'../../../assets/images/carmelitas-moments/carmelitas-factory/5.png',
      alt5:"Image at Carmelita's Factory 5",
      img6: '../../../assets/images/carmelitas-moments/carmelitas-factory/6.png',
      alt6:"Image at Carmelita's Factory 6",
      img7:'../../../assets/images/carmelitas-moments/carmelitas-factory/7.png',
      alt7:"Image at Carmelita's Factory 7",
      img8:'../../../assets/images/carmelitas-moments/carmelitas-factory/8.png',
      alt8:"Image at Carmelita's Factory 8",
      img9:'../../../assets/images/carmelitas-moments/carmelitas-factory/9.png',
      alt9:"Image at Carmelita's Factory 9",
      img10:'../../../assets/images/carmelitas-moments/carmelitas-factory/10.png',
      alt10:"Image at Carmelita's Factory 10",
      img11:'../../../assets/images/carmelitas-moments/carmelitas-factory/11.png',
      alt11:"Image at Carmelita's Factory 11",
      img12:'../../../assets/images/carmelitas-moments/carmelitas-factory/12.png',
      alt12:"Image at Carmelita's Factory 12",
      img13:'../../../assets/images/carmelitas-moments/carmelitas-factory/13.png',
      alt13:"Image at Carmelita's Factory 13",
      img14:'../../../assets/images/carmelitas-moments/carmelitas-factory/14.png',
      alt14:"Image at Carmelita's Factory 14",
      img15:'../../../assets/images/carmelitas-moments/carmelitas-factory/15.png',
      alt15:"Image at Carmelita's Factory 15",
      img16:'../../../assets/images/carmelitas-moments/carmelitas-factory/16.png',
      alt16:"Image at Carmelita's Factory 16",
      img17:'../../../assets/images/carmelitas-moments/carmelitas-factory/17.png',
      alt17:"Image at Carmelita's Factory 17",
    },
    {
      album: 'Rincón Carmelita',
      portada: '../../../assets/images/carmelitas-moments/rincon-carmelita/14.png',
      descportada: 'Cover image at Rincón Carmelita',
      img1: '../../../assets/images/carmelitas-moments/rincon-carmelita/1.png',
      alt1:'Image at Rincón Carmelita 1',
      img2: '../../../assets/images/carmelitas-moments/rincon-carmelita/2.png',
      alt2:'Image at Rincón Carmelita 2',
      img3:'../../../assets/images/carmelitas-moments/rincon-carmelita/3.png',
      alt3:'Image at Rincón Carmelita 3',
      img4: '../../../assets/images/carmelitas-moments/rincon-carmelita/4.png',
      alt4:'Image at Rincón Carmelita 4',
      img5:'../../../assets/images/carmelitas-moments/rincon-carmelita/5.png',
      alt5:'Image at Rincón Carmelita 5',
      img6: '../../../assets/images/carmelitas-moments/rincon-carmelita/6.png',
      alt6:'Image at Rincón Carmelita 6',
      img7:'../../../assets/images/carmelitas-moments/rincon-carmelita/7.png',
      alt7:'Image at Rincón Carmelita 7',
      img8:'../../../assets/images/carmelitas-moments/rincon-carmelita/8.png',
      alt8:'Image at Rincón Carmelita 8',
      img9:'../../../assets/images/carmelitas-moments/rincon-carmelita/9.png',
      alt9:'Image at Rincón Carmelita 9',
      img10:'../../../assets/images/carmelitas-moments/rincon-carmelita/10.png',
      alt10:'Image at Rincón Carmelita 10',
      img11:'../../../assets/images/carmelitas-moments/rincon-carmelita/11.png',
      alt11:'Image at Rincón Carmelita 11',
      img12:'../../../assets/images/carmelitas-moments/rincon-carmelita/12.png',
      alt12:'Image at Rincón Carmelita 12',
      img13:'../../../assets/images/carmelitas-moments/rincon-carmelita/13.png',
      alt13:'Image at Rincón Carmelita 13',
      img14:'../../../assets/images/carmelitas-moments/rincon-carmelita/14.png',
      alt14:'Image at Rincón Carmelita 14',
      img15:'../../../assets/images/carmelitas-moments/rincon-carmelita/15.png',
      alt15:'Image at Rincón Carmelita 15',
      img16:'../../../assets/images/carmelitas-moments/rincon-carmelita/16.png',
      alt16:'Image at Rincón Carmelita 16',
      img17:'../../../assets/images/carmelitas-moments/rincon-carmelita/17.png',
      alt17:'Image at Rincón Carmelita 17',
    },
    {
      album: 'Conference at Vainilla y Chocolate ',
      portada: '../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/3.png',
      descportada: 'Cover image of conference at Vainilla y Chocolate',
      img1: '../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/1.png',
      alt1:'Image of conference at Vainilla y Chocolate 1',
      img2: '../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/2.png',
      alt2:'Image of conference at Vainilla y Chocolate 2',
      img3:'../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/3.png',
      alt3:'Image of conference at Vainilla y Chocolate 3',
      img4: '../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/4.png',
      alt4:'Image of conference at Vainilla y Chocolate 4',
      img5:'../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/5.png',
      alt5:'Image of conference at Vainilla y Chocolate 5',
      img6: '../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/6.png',
      alt6:'Image of conference at Vainilla y Chocolate 6',
      img7:'../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/7.png',
      alt7:'Image of conference at Vainilla y Chocolate 7',
      img8:'../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/8.png',
      alt8:'Image of conference at Vainilla y Chocolate 8',
      img9:'../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/9.png',
      alt9:'Image of conference at Vainilla y Chocolate 9',
      img10:'../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/10.png',
      alt10:'Image of conference at Vainilla y Chocolate 10',
      img11:'../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/11.png',
      alt11:'Image of conference at Vainilla y Chocolate 11',
      img12:'../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/12.png',
      alt12:'Image of conference at Vainilla y Chocolate 12',
      img13:'../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/13.png',
      alt13:'Image of conference at Vainilla y Chocolate 13',
      img14:'../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/14.png',
      alt14:'Image of conference at Vainilla y Chocolate 14',
      img15:'../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/15.png',
      alt15:'Image of conference at Vainilla y Chocolate 15',
      img16:'../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/16.png',
      alt16:'Image of conference at Vainilla y Chocolate 16',
      img17:'../../../assets/images/carmelitas-moments/vainilla-y-chocolate-conference/17.png',
      alt17:'Image of conference at Vainilla y Chocolate 17',
    },
    {
      album: "Winners of Carmelita's contest",
      portada: '../../../assets/images/carmelitas-moments/winners-carmelitas-contest/6.png',
      descportada: "Cover image of winners of Carmelita's contest",
      img1: '../../../assets/images/carmelitas-moments/winners-carmelitas-contest/1.png',
      alt1:"Image of winners of Carmelita's contest 1",
      img2: '../../../assets/images/carmelitas-moments/winners-carmelitas-contest/2.png',
      alt2: "Image of winners of Carmelita's contest 2",
      img3:'../../../assets/images/carmelitas-moments/winners-carmelitas-contest/3.png',
      alt3:"Image of winners of Carmelita's contest 3",
      img4: '../../../assets/images/carmelitas-moments/winners-carmelitas-contest/4.png',
      alt4:"Image of winners of Carmelita's contest 4",
      img5:'../../../assets/images/carmelitas-moments/winners-carmelitas-contest/5.png',
      alt5:"Image of winners of Carmelita's contest 5",
      img6: '../../../assets/images/carmelitas-moments/winners-carmelitas-contest/6.png',
      alt6:"Image of winners of Carmelita's contest 6",
      img7:'../../../assets/images/carmelitas-moments/winners-carmelitas-contest/7.png',
      alt7:"Image of winners of Carmelita's contest 7",
      img8:'../../../assets/images/carmelitas-moments/winners-carmelitas-contest/8.png',
      alt8:"Image of winners of Carmelita's contest 8",
      img9:'../../../assets/images/carmelitas-moments/winners-carmelitas-contest/9.png',
      alt9:"Image of winners of Carmelita's contest 9",
      img10:'../../../assets/images/carmelitas-moments/winners-carmelitas-contest/10.png',
      alt10:"Image of winners of Carmelita's contest 10",
      img11:'../../../assets/images/carmelitas-moments/winners-carmelitas-contest/11.png',
      alt11:"Image of winners of Carmelita's contest 11",
      img12:'../../../assets/images/carmelitas-moments/winners-carmelitas-contest/12.png',
      alt12:"Image of winners of Carmelita's contest 12",
      img13:'../../../assets/images/carmelitas-moments/winners-carmelitas-contest/13.png',
      alt13:"Image of winners of Carmelita's contest 13",
      img14:'../../../assets/images/carmelitas-moments/winners-carmelitas-contest/14.png',
      alt14:"Image of winners of Carmelita's contest 14",
      img15:'../../../assets/images/carmelitas-moments/winners-carmelitas-contest/15.png',
      alt15:"Image of winners of Carmelita's contest 15",
      img16:'../../../assets/images/carmelitas-moments/winners-carmelitas-contest/16.png',
      alt16:"Image of winners of Carmelita's contest 16",
      img17:'../../../assets/images/carmelitas-moments/winners-carmelitas-contest/17.png',
      alt17:"Image of winners of Carmelita's contest 17",
    },
    {
      album: "Beach 2020 - Carmelita's Team",
      portada: '../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/portada-playa.png',
      descportada: "Cover image of Beach 2020 - Carmelita's Team",
      img1: '../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/1.png',
      alt1:"Image of Beach 2020 - Carmelita's Team 1",
      img2: '../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/2.png',
      alt2:"Image of Beach 2020 - Carmelita's Team 2",
      img3:'../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/3.png',
      alt3:"Image of Beach 2020 - Carmelita's Team 3",
      img4: '../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/4.png',
      alt4:"Image of Beach 2020 - Carmelita's Team 4",
      img5:'../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/5.png',
      alt5:"Image of Beach 2020 - Carmelita's Team 5",
      img6: '../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/6.png',
      alt6:"Image of Beach 2020 - Carmelita's Team 6",
      img7:'../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/7.png',
      alt7:"Image of Beach 2020 - Carmelita's Team 7",
      img8:'../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/8.png',
      alt8:"Image of Beach 2020 - Carmelita's Team 8",
      img9:'../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/9.png',
      alt9:"Image of Beach 2020 - Carmelita's Team 9",
      img10:'../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/10.png',
      alt10:"Image of Beach 2020 - Carmelita's Team 10",
      img11:'../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/11.png',
      alt11:"Image of Beach 2020 - Carmelita's Team 11",
      img12:'../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/12.png',
      alt12:"Image of Beach 2020 - Carmelita's Team 12",
      img13:'../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/13.png',
      alt13:"Image of Beach 2020 - Carmelita's Team 13",
      img14:'../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/14.png',
      alt14:"Image of Beach 2020 - Carmelita's Team 14",
      img15:'../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/15.png',
      alt15:"Image of Beach 2020 - Carmelita's Team 15",
      img16:'../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/portada-playa.png',
      alt16:"Image of Beach 2020 - Carmelita's Team 16",
      img17:'../../../assets/images/carmelitas-moments/beach-2020-carmelitas-team/17.png',
      alt17:"Image of Beach 2020 - Carmelita's Team 17",
    },
    {
      album: "Carmelita's Christmas Party 2020",
      portada: '../../../assets/images/carmelitas-moments/christmas-party-2020/6.png',
      descportada: "Cover image of Carmelita's Christmas Party 2020",
      img1: '../../../assets/images/carmelitas-moments/christmas-party-2020/1.png',
      alt1:"Image of Carmelita's Christmas Party 2020 - 1",
      img2: '../../../assets/images/carmelitas-moments/christmas-party-2020/2.png',
      alt2:"Image of Carmelita's Christmas Party 2020 - 2",
      img3:'../../../assets/images/carmelitas-moments/christmas-party-2020/3.png',
      alt3:"Image of Carmelita's Christmas Party 2020 - 3",
      img4: '../../../assets/images/carmelitas-moments/christmas-party-2020/4.png',
      alt4:"Image of Carmelita's Christmas Party 2020 - 4",
      img5:'../../../assets/images/carmelitas-moments/christmas-party-2020/5.png',
      alt5:"Image of Carmelita's Christmas Party 2020 - 5",
      img6: '../../../assets/images/carmelitas-moments/christmas-party-2020/6.png',
      alt6:"Image of Carmelita's Christmas Party 2020 - 6",
      img7:'../../../assets/images/carmelitas-moments/christmas-party-2020/7.png',
      alt7:"Image of Carmelita's Christmas Party 2020 - 7",
      img8:'../../../assets/images/carmelitas-moments/christmas-party-2020/8.png',
      alt8:"Image of Carmelita's Christmas Party 2020 - 8",
      img9:'../../../assets/images/carmelitas-moments/christmas-party-2020/9.png',
      alt9:"Image of Carmelita's Christmas Party 2020 - 9",
      img10:'../../../assets/images/carmelitas-moments/christmas-party-2020/10.png',
      alt10:"Image of Carmelita's Christmas Party 2020 - 10",
      img11:'../../../assets/images/carmelitas-moments/christmas-party-2020/11.png',
      alt11:"Image of Carmelita's Christmas Party 2020 - 11",
      img12:'../../../assets/images/carmelitas-moments/christmas-party-2020/12.png',
      alt12:"Image of Carmelita's Christmas Party 2020 - 12",
      img13:'../../../assets/images/carmelitas-moments/christmas-party-2020/13.png',
      alt13:"Image of Carmelita's Christmas Party 2020 13",
      img14:'../../../assets/images/carmelitas-moments/christmas-party-2020/14.png',
      alt14:"Image of Carmelita's Christmas Party 2020 - 14",
      img15:'../../../assets/images/carmelitas-moments/christmas-party-2020/15.png',
      alt15:"Image of Carmelita's Christmas Party 2020 - 15",
      img16:'../../../assets/images/carmelitas-moments/christmas-party-2020/16.png',
      alt16:"Image of Carmelita's Christmas Party 2020 - 16",
      img17:'../../../assets/images/carmelitas-moments/christmas-party-2020/17.png',
      alt17:"Image of Carmelita's Christmas Party 2020 - 17",
    },
  ]

  constructor() { }
  obtenerMomento(){
    return this.momentosc;
  }
  obtenerVistaMomento(i){
    return this.momentosc[i];
  }
}
